### ISSUE TITLE
red errors

### ISSUE THREAD

**Issue by stunlocked1** [Daria40K/Mighty-Persona-Bond-Forge-Patch-Mod#2]
there are a few XML errrors probably because MODs changed stuff after 1.4 update
- Make_VFEP_WarcasketGun_LaserBlaster_Bond: 
`Could not resolve cross-reference to Verse.ResearchProjectDef named VWE_UltratechLaserWeapons (wanter=researchPrerequisites)`
- CodZP_Gun_LMG-Persona: 
`Could not resolve cross-reference: No Verse.ThingDef named CodZP_Bullet_PAP_LMG_Bond found to give to Verse.VerbProperties VerbProperties(Persona Laminate Machine Gun)`
- CodZP_Bullet_PAP_SmokeLauncher_Bond: 
`Could not resolve cross-reference: No Verse.ThingDef named Gas_Smoke found to give to Verse.ProjectileProperties Verse.ProjectileProperties`
- Make_VFEP_WarcasketGun_LaserBlaster_Bond: 
`Could not resolve cross-reference to Verse.ThingDef named VFEP_WarcasketGun_LaserBlaster (wanter=thingDefs)`
- Make_VFEP_WarcasketGun_SalvagedLaserEradicator_Bond: 
`Could not resolve cross-reference to Verse.ThingDef named VFEP_WarcasketGun_SalvagedLaserEradicator (wanter=thingDefs) `
- `VSWBG_Bullet_RepulseRifle_ParticlePulsebeam_Bond is missing thing class and will not work properly. Report about it to  devs. ` - BounceGun.BulletBouncer was changed to BounceGun.RicochetBullet in last update
- `Could not find type named BounceGun.BounceProps from node <li Class="BounceGun.BounceProps">` idk where this one went but new version doesn't have any modExtensions

**Comment by Daria40K** [comment]
v3.15.1 has fixed XML errors for Call of Duty: Zombies Pack and Vanilla Spacer weapons - Bounce Gun but i'm still looking into the other stuff

**Comment by Daria40K** [comment]
Unable to get the rest of the errors myself. Also in the future providing a Hubslib error log would of helped.
